name: deploy

on:
  workflow_dispatch:
  schedule:
    # every week on Friday at 23:00 JST = 14:00 UTC
    - cron: '0 14 * * 5'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: run scripts
        run: |
          mkdir /public
          node main.mjs > /public/lineup.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

